<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>GOG Physical Disc Creator</AssemblyName>
    <Product>GOG Physical Disc Creator</Product>
    <RootNamespace>GogDisc.Packager</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>None</DebugType>
    <ApplicationIcon>..\..\assets\PhysicalDiscCreator.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GogDisc.Core\GogDisc.Core.csproj" />
  </ItemGroup>
</Project>
