<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Launch</AssemblyName>
    <RootNamespace>GogDisc.Launcher</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GogDisc.Core\GogDisc.Core.csproj" />
    <Resource Include="Assets\DefaultBackground.png" />
    <Resource Include="Assets\DefaultCover.png" />
    <Resource Include="Assets\DefaultIcon.png" />
  </ItemGroup>
</Project>
